// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/parser/tests/packet.test.ts
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
import { describe, expect, it } from 'vitest';

import { Packet } from './adapter.js';
import { expectNoErrorsOrAlternatives, packetParse as parse } from './adapter.js';

describe('packet', () => {
  it.each([
    `packet-beta`,
    `  packet-beta  `,
    `\tpacket-beta\t`,
    `
    \tpacket-beta
    `,
    `packet`,
    `  packet  `,
    `\tpacket\t`,
    `
    \tpacket
    `,
  ])('should handle regular packet', (context: string) => {
    const result = parse(context);
    expectNoErrorsOrAlternatives(result);
    expect(result.value.$type).toBe(Packet.$type);
  });
});
