// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/mermaid/src/diagrams/ishikawa/ishikawa.spec.ts
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
// @ts-expect-error No types available for JISON
import { parser as ishikawa } from './adapter.js';
import { IshikawaDB } from './adapter.js';
import { setLogLevel } from './adapter.js';

describe('when parsing an Ishikawa diagram', function () {
  beforeEach(function () {
    ishikawa.yy = new IshikawaDB();
    ishikawa.yy.clear();
    setLogLevel('trace');
  });

  it('should parse a basic Ishikawa hierarchy', function () {
    const str = `ishikawa-beta
    Blurry Photo
        Process
            Out of focus
        User
            Shaky hands
`;

    ishikawa.parse(str);
    const root = ishikawa.yy.getRoot();
    expect(root?.text).toEqual('Blurry Photo');
    expect(root?.children.length).toEqual(2);
    expect(root?.children[0].text).toEqual('Process');
    expect(root?.children[0].children[0].text).toEqual('Out of focus');
    expect(root?.children[1].text).toEqual('User');
    expect(root?.children[1].children[0].text).toEqual('Shaky hands');
  });

  it('should support an unindented root with nested causes', function () {
    const str = `ishikawa-beta
Problem
Cause A
  Subcause A1
Cause B
`;

    ishikawa.parse(str);
    const root = ishikawa.yy.getRoot();
    expect(root?.text).toEqual('Problem');
    expect(root?.children.length).toEqual(2);
    expect(root?.children[0].text).toEqual('Cause A');
    expect(root?.children[0].children[0].text).toEqual('Subcause A1');
    expect(root?.children[1].text).toEqual('Cause B');
  });

  it('should handle effect indented more than causes', function () {
    const str = `ishikawa-beta
    Problem
Cause A
  Subcause A1
Cause B
`;

    ishikawa.parse(str);
    const root = ishikawa.yy.getRoot();
    expect(root?.text).toEqual('Problem');
    expect(root?.children.length).toEqual(2);
    expect(root?.children[0].text).toEqual('Cause A');
    expect(root?.children[0].children.length).toEqual(1);
    expect(root?.children[0].children[0].text).toEqual('Subcause A1');
    expect(root?.children[1].text).toEqual('Cause B');
  });
});
