// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/mermaid/src/diagrams/class/parser/class.spec.js
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
import { parser } from './adapter.js';
import { ClassDB } from './adapter.js';

describe('class diagram', function () {
  let classDb;
  beforeEach(function () {
    classDb = new ClassDB();
    parser.yy = classDb;
    parser.yy.clear();
  });

  describe('prototype properties', function () {
    it.each(['__proto__', 'constructor'])('should work with a %s property', function (prop) {
      expect(() => parser.parse(`classDiagram\nclass ${prop}`)).not.toThrow();
      expect(() => parser.parse(`classDiagram\nnamespace ${prop} {\n\tclass A\n}`)).not.toThrow();
    });
  });

  describe('backtick escaping', function () {
    it('should handle backtick-quoted namespace names', function () {
      expect(() =>
        parser.parse(`classDiagram\nnamespace \`A::B\` {\n\tclass \`IPC::Sender\`\n}`)
      ).not.toThrow();
    });
  });
});
