// Reads advance widths for printable ASCII from TrueType fonts and writes src/text/metrics.ts.
// Usage: node scripts/gen-metrics.mjs <regular.ttf> <bold.ttf>
import { readFileSync, writeFileSync } from 'node:fs';

function widths(path) {
  const buf = readFileSync(path);
  const tables = {};
  const count = buf.readUInt16BE(4);
  for (let i = 0; i < count; i++) {
    const at = 12 + i * 16;
    tables[buf.toString('latin1', at, at + 4)] = buf.readUInt32BE(at + 8);
  }
  const unitsPerEm = buf.readUInt16BE(tables.head + 18);
  const numHMetrics = buf.readUInt16BE(tables.hhea + 34);
  const advance = (glyph) => buf.readUInt16BE(tables.hmtx + Math.min(glyph, numHMetrics - 1) * 4);

  let sub = -1;
  const cmap = tables.cmap;
  for (let i = 0; i < buf.readUInt16BE(cmap + 2); i++) {
    const rec = cmap + 4 + i * 8;
    const platform = buf.readUInt16BE(rec);
    const encoding = buf.readUInt16BE(rec + 2);
    const offset = cmap + buf.readUInt32BE(rec + 4);
    if (buf.readUInt16BE(offset) === 4 && (platform === 0 || (platform === 3 && encoding === 1))) sub = offset;
  }
  if (sub < 0) throw new Error('No format 4 cmap in ' + path);
  const segX2 = buf.readUInt16BE(sub + 6);
  const ends = sub + 14;
  const startsAt = ends + segX2 + 2;
  const deltas = startsAt + segX2;
  const ranges = deltas + segX2;
  const glyphFor = (code) => {
    for (let s = 0; s < segX2; s += 2) {
      if (buf.readUInt16BE(ends + s) < code) continue;
      const start = buf.readUInt16BE(startsAt + s);
      if (start > code) return 0;
      const delta = buf.readInt16BE(deltas + s);
      const range = buf.readUInt16BE(ranges + s);
      if (range === 0) return (code + delta) & 0xffff;
      const glyph = buf.readUInt16BE(ranges + s + range + (code - start) * 2);
      return glyph === 0 ? 0 : (glyph + delta) & 0xffff;
    }
    return 0;
  };
  let out = '';
  for (let code = 32; code < 127; code++) {
    const w = Math.round((advance(glyphFor(code)) * 1000) / unitsPerEm);
    out += w.toString(36).padStart(2, '0');
  }
  return out;
}

const [regular, bold] = process.argv.slice(2);
writeFileSync(
  'src/text/metrics.ts',
  `// Advance widths of printable ASCII in thousandths of an em, two base-36 digits each.\n` +
    `// Generated by scripts/gen-metrics.mjs from Arial.\n` +
    `export const REGULAR =\n  '${widths(regular)}';\n` +
    `export const BOLD =\n  '${widths(bold)}';\n`
);
