// Copies Mermaid's parser specs into tests/compat and points their imports at Pele's adapters.
// Usage: node scripts/sync-specs.mjs <path to a mermaid checkout at the pinned tag> [suite]
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.argv[2];
if (!root) throw new Error('Pass the path to a mermaid checkout.');
const tags = execFileSync('git', ['-C', root, 'tag', '--points-at', 'HEAD'], { encoding: 'utf8' }).split('\n');
const tag = tags.find((t) => t.startsWith('mermaid@')) ?? tags[0];
const commit = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
const diagrams = join(root, 'packages/mermaid/src/diagrams');

// Each file in scripts/suites describes one diagram type:
//   files      [directory under packages/mermaid/src/diagrams, filename pattern] pairs to copy
//   grammars   grammar files to vendor next to the specs, for the reference parser used in tests
//   docs       file under packages/mermaid/src/docs/syntax whose examples become a test corpus
//   rewrite    [pattern, replacement] pairs applied to each spec, to point imports at the adapter
//   skip       tests to skip, each with a reason
//   notPorted  spec files left out, each with a reason
const SUITES = {};
for (const file of readdirSync(new URL('./suites/', import.meta.url)).filter((f) => f.endsWith('.mjs')).sort()) {
  SUITES[file.replace(/\.mjs$/, '')] = (await import(new URL(`./suites/${file}`, import.meta.url).href)).default;
}
const only = process.argv[3];

for (const [name, suite] of Object.entries(SUITES)) {
  if (only && only !== name) continue;
  const out = join('tests/compat', name);
  mkdirSync(join(out, 'upstream'), { recursive: true });
  for (const grammar of suite.grammars ?? []) {
    writeFileSync(join(out, 'upstream', grammar.split('/').pop()), readFileSync(join(diagrams, grammar)));
  }
  let count = 0;
  for (const [dir, pattern] of suite.files) {
    // A directory starting with a slash is relative to the Mermaid repository, not to its diagrams folder.
    const from = dir.startsWith('/') ? join(root, dir) : join(diagrams, dir);
    const origin = dir.startsWith('/') ? dir.slice(1) : `packages/mermaid/src/diagrams/${dir}`;
    for (const file of readdirSync(from).filter((f) => pattern.test(f))) {
      let src = readFileSync(join(from, file), 'utf8');
      for (const [from, to] of suite.rewrite) src = src.replace(from, to);
      for (const skip of (suite.skip ?? []).filter((entry) => entry.file === file)) {
        const quoted = [`'${skip.test.replace(/'/g, "\\'")}'`, JSON.stringify(skip.test)];
        const at = quoted.map((q) => src.indexOf(`it(${q}`)).find((index) => index !== -1);
        if (at === undefined) throw new Error(`Skipped test not found in ${file}: ${skip.test}`);
        src = src.slice(0, at) + 'it.skip(' + src.slice(at + 3);
      }
      const header =
        `// Ported from Mermaid ${tag} (${commit.slice(0, 10)}), ${origin}/${file}\n` +
        `// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.\n`;
      writeFileSync(join(out, file), header + src);
      count++;
    }
  }
  if (suite.docs) {
    const md = readFileSync(join(root, 'packages/mermaid/src/docs/syntax', suite.docs), 'utf8');
    const samples = [...md.matchAll(/```(?:mermaid[-\w]*|mmd)\n([\s\S]*?)```/g)].map((m) => m[1]);
    mkdirSync('tests/corpus', { recursive: true });
    writeFileSync(join('tests/corpus', `${name}-docs.json`), JSON.stringify([...new Set(samples)], null, 1) + '\n');
  }
  const lines = [
    `# Skipped ${name} specs`,
    '',
    `Ported from Mermaid ${tag}. Generated by \`scripts/sync-specs.mjs\`.`,
    '',
    '## Skipped tests',
    '',
    ...(suite.skip ?? []).map((entry) => `- \`${entry.file}\`: "${entry.test}". ${entry.reason}`),
    '',
    '## Spec files not ported',
    '',
    ...(suite.notPorted ?? []).map(([file, reason]) => `- \`${file}\`: ${reason}`),
    '',
  ];
  writeFileSync(join(out, 'SKIPPED.md'), lines.join('\n'));
  console.log(`${name}: ${count} spec files from ${tag}`);
}
