// Copies Mermaid's parser specs into tests/compat and points their imports at Pele's adapters.
// Usage: node scripts/sync-specs.mjs <path to a mermaid checkout at the pinned tag>
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.argv[2];
if (!root) throw new Error('Pass the path to a mermaid checkout.');
const tags = execFileSync('git', ['-C', root, 'tag', '--points-at', 'HEAD'], { encoding: 'utf8' }).split('\n');
const tag = tags.find((t) => t.startsWith('mermaid@')) ?? tags[0];
const commit = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
const diagrams = join(root, 'packages/mermaid/src/diagrams');

const SUITES = {
  flowchart: {
    files: [['flowchart/parser', /\.spec\.js$/], ['flowchart', /^flowDb\.spec\.ts$/]],
    grammars: ['flowchart/parser/flow.jison'],
    docs: 'flowchart.md',
    skip: [
      {
        file: 'flow.spec.js',
        test: "should be able to parse a '<'",
        reason:
          "Expects the label `<` to be stored as `&lt;`, which is DOMPurify's serialization. Pele stores label text as written and escapes it when writing SVG.",
      },
      {
        file: 'flowDb.spec.ts',
        test: 'should have functions used in flow JISON as own property',
        reason:
          'Checks that FlowDB methods are own properties, a requirement of the Jison runtime. Pele has no Jison runtime.',
      },
    ],
    notPorted: [
      ['flowChartShapes.spec.js', "Tests Mermaid's legacy dagre-d3 shape renderer."],
      ['flowDiagram.spec.ts', "Tests Mermaid's diagram registration and config plumbing."],
      ['flowRenderer-elk-default.spec.ts', "Tests Mermaid's choice between its dagre and ELK layout engines."],
      ['flowRenderer-v3-unified.spec.ts', "Tests Mermaid's DOM renderer wiring."],
      [
        'flowDb-elk-duplicate-subgraph.spec.ts',
        'Runs ELK layout. Its parsing half, a repeated subgraph id merging into one subgraph, is covered in tests/flowchart/parser.test.ts.',
      ],
    ],
    rewrite: [
      [/from '(?:\.\.\/|\.\/)flowDb\.js'/g, "from './adapter.js'"],
      [/from '(?:\.\/parser\/|\.\/)flowParser\.(?:ts|js)'/g, "from './adapter.js'"],
      [/from '\.\.\/\.\.\/\.\.\/config\.js'/g, "from './adapter.js'"],
      [/from '\.\.\/\.\.\/\.\.\/diagram-api\/comments\.js'/g, "from './adapter.js'"],
      [/from '\.\/types\.js'/g, "from './adapter.js'"],
      [/from '\.\.\/\.\.\/\.\.\/logger\.js'/g, "from './adapter.js'"],
    ],
  },
};

for (const [name, suite] of Object.entries(SUITES)) {
  const out = join('tests/compat', name);
  mkdirSync(join(out, 'upstream'), { recursive: true });
  for (const grammar of suite.grammars) {
    writeFileSync(join(out, 'upstream', grammar.split('/').pop()), readFileSync(join(diagrams, grammar)));
  }
  let count = 0;
  for (const [dir, pattern] of suite.files) {
    for (const file of readdirSync(join(diagrams, dir)).filter((f) => pattern.test(f))) {
      let src = readFileSync(join(diagrams, dir, file), 'utf8');
      for (const [from, to] of suite.rewrite) src = src.replace(from, to);
      for (const skip of suite.skip.filter((entry) => entry.file === file)) {
        const quoted = [`'${skip.test.replace(/'/g, "\\'")}'`, JSON.stringify(skip.test)];
        const at = quoted.map((q) => src.indexOf(`it(${q}`)).find((index) => index !== -1);
        if (at === undefined) throw new Error(`Skipped test not found in ${file}: ${skip.test}`);
        src = src.slice(0, at) + 'it.skip(' + src.slice(at + 3);
      }
      const header =
        `// Ported from Mermaid ${tag} (${commit.slice(0, 10)}), packages/mermaid/src/diagrams/${dir}/${file}\n` +
        `// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.\n`;
      writeFileSync(join(out, file), header + src);
      count++;
    }
  }
  if (suite.docs) {
    const md = readFileSync(join(root, 'packages/mermaid/src/docs/syntax', suite.docs), 'utf8');
    const samples = [...md.matchAll(/```(?:mermaid[-\w]*|mmd)\n([\s\S]*?)```/g)].map((m) => m[1]);
    mkdirSync('tests/corpus', { recursive: true });
    writeFileSync(join('tests/corpus', `${name}-docs.json`), JSON.stringify([...new Set(samples)], null, 1) + '\n');
  }
  const lines = [
    `# Skipped ${name} specs`,
    '',
    `Ported from Mermaid ${tag}. Generated by \`scripts/sync-specs.mjs\`.`,
    '',
    '## Skipped tests',
    '',
    ...suite.skip.map((entry) => `- \`${entry.file}\`: "${entry.test}". ${entry.reason}`),
    '',
    '## Spec files not ported',
    '',
    ...suite.notPorted.map(([file, reason]) => `- \`${file}\`: ${reason}`),
    '',
  ];
  writeFileSync(join(out, 'SKIPPED.md'), lines.join('\n'));
  console.log(`${name}: ${count} spec files from ${tag}`);
}
