// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/mermaid/src/diagrams/info/info.spec.ts
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
import { parser } from './adapter.js';

describe('info', () => {
  it('should handle an info definition', async () => {
    const str = `info`;
    await expect(parser.parse(str)).resolves.not.toThrow();
  });

  it('should handle an info definition with showInfo', async () => {
    const str = `info showInfo`;
    await expect(parser.parse(str)).resolves.not.toThrow();
  });

  it.skip('should throw because of unsupported info grammar', async () => {
    const str = `info unsupported`;
    await expect(parser.parse(str)).rejects.toThrow(
      'Parsing failed: Lexer error on line 1, column 6: unexpected character: ->u<- at offset: 5, skipped 11 characters.'
    );
  });

  it.skip('should throw because of unsupported info grammar', async () => {
    const str = `info unsupported`;
    await expect(parser.parse(str)).rejects.toThrow(
      'Parsing failed: Lexer error on line 1, column 6: unexpected character: ->u<- at offset: 5, skipped 11 characters.'
    );
  });
});
