// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/parser/tests/info.test.ts
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
import { describe, expect, it } from 'vitest';

import { Info } from './adapter.js';
import { expectNoErrorsOrAlternatives, infoParse as parse } from './adapter.js';

describe('info', () => {
  it.each([
    `info`,
    `
    info`,
    `info
    `,
    `
    info
    `,
  ])('should handle empty info', (context: string) => {
    const result = parse(context);
    expectNoErrorsOrAlternatives(result);
    expect(result.value.$type).toBe(Info.$type);
  });

  it.each([
    `info showInfo`,
    `info showInfo
    `,
    `
    info showInfo`,
    `info
    showInfo`,
    `info
    showInfo
    `,
    `
    info
    showInfo
    `,
    `
    info
    showInfo`,
    `
    info showInfo
    `,
  ])('should handle showInfo', (context: string) => {
    const result = parse(context);
    expectNoErrorsOrAlternatives(result);
    expect(result.value.$type).toBe(Info.$type);
  });
});
