// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/mermaid/src/diagrams/railroad/ebnfDetector.spec.ts
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
import { describe, it, expect } from 'vitest';
import { railroadEbnf } from './adapter.js';

describe('EBNF Detector', () => {
  it('should have correct id', () => {
    expect(railroadEbnf.id).toBe('railroadEbnf');
  });

  it('should detect railroad-ebnf-beta keyword', () => {
    expect(railroadEbnf.detector('railroad-ebnf-beta\nrule = "test" ;')).toBe(true);
  });

  it('should detect with leading whitespace', () => {
    expect(railroadEbnf.detector('  railroad-ebnf-beta\nrule = "test" ;')).toBe(true);
  });

  it('should detect case-insensitively', () => {
    expect(railroadEbnf.detector('RAILROAD-EBNF-BETA\nrule = "test" ;')).toBe(true);
  });

  it('should not detect other diagram types', () => {
    expect(railroadEbnf.detector('railroad-beta\nrule = terminal("a") ;')).toBe(false);
    expect(railroadEbnf.detector('flowchart TD\nA --> B')).toBe(false);
  });

  it('should load the diagram', async () => {
    const result = await railroadEbnf.loader();
    expect(result.id).toBe('railroadEbnf');
    expect(result.diagram).toBeDefined();
    expect(result.diagram.parser).toBeDefined();
    expect(result.diagram.db).toBeDefined();
    expect(result.diagram.renderer).toBeDefined();
  });
});
