// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/mermaid/src/diagrams/railroad/pegDetector.spec.ts
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
import { describe, it, expect } from 'vitest';
import { railroadPeg } from './adapter.js';

describe('PEG Detector', () => {
  it('should have correct id', () => {
    expect(railroadPeg.id).toBe('railroadPeg');
  });

  it('should detect railroad-peg-beta keyword', () => {
    expect(railroadPeg.detector('railroad-peg-beta\nrule <- "test" ;')).toBe(true);
  });

  it('should detect with leading whitespace', () => {
    expect(railroadPeg.detector('  railroad-peg-beta\nrule <- "test" ;')).toBe(true);
  });

  it('should detect case-insensitively', () => {
    expect(railroadPeg.detector('RAILROAD-PEG-BETA\nrule <- "test" ;')).toBe(true);
  });

  it('should not detect other diagram types', () => {
    expect(railroadPeg.detector('railroad-beta\nrule = terminal("a") ;')).toBe(false);
    expect(railroadPeg.detector('flowchart TD\nA --> B')).toBe(false);
  });

  it('should load the diagram', async () => {
    const result = await railroadPeg.loader();
    expect(result.id).toBe('railroadPeg');
    expect(result.diagram).toBeDefined();
    expect(result.diagram.parser).toBeDefined();
    expect(result.diagram.db).toBeDefined();
    expect(result.diagram.renderer).toBeDefined();
  });
});
