import { detectType, mount, register, registered, render, type DiagramType, type MountOptions, type Mounted, type RenderOptions, type RenderResult } from './core.js';
import type { Diagram } from './types.js';

export * from './core.js';
export type * from './models.js';

// Generated by scripts/gen-registry.mjs.
const loaders = new Map<DiagramType, () => Promise<Diagram<unknown>>>([
  ['flowchart', () => import('./diagrams/flowchart/index.js').then((m) => m.flowchart as Diagram<unknown>)],
  ['pie', () => import('./diagrams/pie/index.js').then((m) => m.pie as Diagram<unknown>)],
  ['er', () => import('./diagrams/er/index.js').then((m) => m.er as Diagram<unknown>)],
  ['mindmap', () => import('./diagrams/mindmap/index.js').then((m) => m.mindmap as Diagram<unknown>)],
  ['kanban', () => import('./diagrams/kanban/index.js').then((m) => m.kanban as Diagram<unknown>)],
  ['timeline', () => import('./diagrams/timeline/index.js').then((m) => m.timeline as Diagram<unknown>)],
  ['journey', () => import('./diagrams/journey/index.js').then((m) => m.journey as Diagram<unknown>)],
  ['class', () => import('./diagrams/class/index.js').then((m) => m.classDiagram as Diagram<unknown>)],
  ['quadrantChart', () => import('./diagrams/quadrant/index.js').then((m) => m.quadrantChart as Diagram<unknown>)],
  ['xychart', () => import('./diagrams/xychart/index.js').then((m) => m.xychart as Diagram<unknown>)],
  ['state', () => import('./diagrams/state/index.js').then((m) => m.state as Diagram<unknown>)],
  ['gantt', () => import('./diagrams/gantt/index.js').then((m) => m.gantt as Diagram<unknown>)],
  ['architecture', () => import('./diagrams/architecture/index.js').then((m) => m.architecture as Diagram<unknown>)],
  ['requirement', () => import('./diagrams/requirement/index.js').then((m) => m.requirement as Diagram<unknown>)],
  ['sankey', () => import('./diagrams/sankey/index.js').then((m) => m.sankey as Diagram<unknown>)],
  ['packet', () => import('./diagrams/packet/index.js').then((m) => m.packet as Diagram<unknown>)],
  ['radar', () => import('./diagrams/radar/index.js').then((m) => m.radar as Diagram<unknown>)],
  ['treemap', () => import('./diagrams/treemap/index.js').then((m) => m.treemap as Diagram<unknown>)],
  ['info', () => import('./diagrams/info/index.js').then((m) => m.info as Diagram<unknown>)],
  ['sequence', () => import('./diagrams/sequence/index.js').then((m) => m.sequence as Diagram<unknown>)],
  ['gitGraph', () => import('./diagrams/git/index.js').then((m) => m.gitGraph as Diagram<unknown>)],
  ['c4', () => import('./diagrams/c4/index.js').then((m) => m.c4 as Diagram<unknown>)],
  ['block', () => import('./diagrams/block/index.js').then((m) => m.block as Diagram<unknown>)],
  ['railroad', () => import('./diagrams/railroad/index.js').then((m) => m.railroad as Diagram<unknown>)],
  ['agentflow', () => import('./diagrams/agentflow/index.js').then((m) => m.agentflow as Diagram<unknown>)],
  ['treeView', () => import('./diagrams/treeview/index.js').then((m) => m.treeView as Diagram<unknown>)],
  ['cynefin', () => import('./diagrams/cynefin/index.js').then((m) => m.cynefin as Diagram<unknown>)],
  ['wardley', () => import('./diagrams/wardley/index.js').then((m) => m.wardley as Diagram<unknown>)],
  ['eventmodeling', () => import('./diagrams/eventmodeling/index.js').then((m) => m.eventmodeling as Diagram<unknown>)],
  ['usecase', () => import('./diagrams/usecase/index.js').then((m) => m.usecase as Diagram<unknown>)],
  ['venn', () => import('./diagrams/venn/index.js').then((m) => m.venn as Diagram<unknown>)],
  ['ishikawa', () => import('./diagrams/ishikawa/index.js').then((m) => m.ishikawa as Diagram<unknown>)],
  ['swimlane', () => import('./diagrams/swimlane/index.js').then((m) => m.swimlane as Diagram<unknown>)],
]);

const pending = new Map<DiagramType, Promise<boolean>>();

// Loads and registers one diagram type. Resolves to false for a type Pele does not draw.
export function load(type: DiagramType | null): Promise<boolean> {
  if (type === null) return Promise.resolve(false);
  if (registered(type)) return Promise.resolve(true);
  let promise = pending.get(type);
  if (promise === undefined) {
    const loader = loaders.get(type);
    if (loader === undefined) return Promise.resolve(false);
    promise = loader().then(
      (diagram) => {
        register(diagram);
        return true;
      },
      (error) => {
        pending.delete(type);
        throw error;
      }
    );
    pending.set(type, promise);
  }
  return promise;
}

// Loads the diagram type that the text needs, then renders it.
export async function renderAsync(text: string, options: RenderOptions = {}): Promise<RenderResult> {
  let type: DiagramType | null = null;
  try {
    type = detectType(text);
  } catch {
    // render() reports what is wrong with the text.
  }
  await load(type);
  return render(text, options);
}

// Loads the diagram type that the text needs, then mounts it. A later update() to another
// type needs that type loaded first.
export async function mountAsync(element: HTMLElement, text: string, options: MountOptions = {}): Promise<Mounted> {
  let type: DiagramType | null = null;
  try {
    type = detectType(text);
  } catch {
    // mount() reports what is wrong with the text.
  }
  await load(type);
  return mount(element, text, options);
}
