// Generated by scripts/gen-registry.mjs.
import type { AgentflowModel } from './diagrams/agentflow/types.js';
import type { ArchitectureModel } from './diagrams/architecture/db.js';
import type { BlockModel } from './diagrams/block/types.js';
import type { C4Model } from './diagrams/c4/types.js';
import type { ClassModel } from './diagrams/class/types.js';
import type { CynefinModel } from './diagrams/cynefin/model.js';
import type { ErModel } from './diagrams/er/types.js';
import type { EventModelingModel } from './diagrams/eventmodeling/model.js';
import type { FlowchartModel } from './diagrams/flowchart/types.js';
import type { GanttModel } from './diagrams/gantt/types.js';
import type { GitModel } from './diagrams/git/db.js';
import type { InfoModel } from './diagrams/info/model.js';
import type { IshikawaModel } from './diagrams/ishikawa/types.js';
import type { JourneyModel } from './diagrams/journey/db.js';
import type { KanbanModel } from './diagrams/kanban/db.js';
import type { MindmapModel } from './diagrams/mindmap/db.js';
import type { PacketModel } from './diagrams/packet/model.js';
import type { PieModel } from './diagrams/pie/model.js';
import type { QuadrantModel } from './diagrams/quadrant/db.js';
import type { RadarModel } from './diagrams/radar/model.js';
import type { RailroadModel } from './diagrams/railroad/types.js';
import type { RequirementModel } from './diagrams/requirement/types.js';
import type { SankeyModel } from './diagrams/sankey/db.js';
import type { SequenceModel } from './diagrams/sequence/types.js';
import type { StateModel } from './diagrams/state/types.js';
import type { SwimlaneModel } from './diagrams/swimlane/index.js';
import type { TimelineModel } from './diagrams/timeline/db.js';
import type { TreeViewModel } from './diagrams/treeview/model.js';
import type { TreemapModel } from './diagrams/treemap/model.js';
import type { UsecaseModel } from './diagrams/usecase/types.js';
import type { VennModel } from './diagrams/venn/types.js';
import type { WardleyModel } from './diagrams/wardley/model.js';
import type { XyChartModel } from './diagrams/xychart/db.js';

export type {
  FlowchartModel,
  PieModel,
  ErModel,
  MindmapModel,
  KanbanModel,
  TimelineModel,
  JourneyModel,
  ClassModel,
  QuadrantModel,
  XyChartModel,
  StateModel,
  GanttModel,
  ArchitectureModel,
  RequirementModel,
  SankeyModel,
  PacketModel,
  RadarModel,
  TreemapModel,
  InfoModel,
  SequenceModel,
  GitModel,
  C4Model,
  BlockModel,
  RailroadModel,
  AgentflowModel,
  TreeViewModel,
  CynefinModel,
  WardleyModel,
  EventModelingModel,
  UsecaseModel,
  VennModel,
  IshikawaModel,
  SwimlaneModel,
};

// The union of every implemented diagram's model; narrow it with its `type` field.
export type DiagramModel =
  | FlowchartModel
  | PieModel
  | ErModel
  | MindmapModel
  | KanbanModel
  | TimelineModel
  | JourneyModel
  | ClassModel
  | QuadrantModel
  | XyChartModel
  | StateModel
  | GanttModel
  | ArchitectureModel
  | RequirementModel
  | SankeyModel
  | PacketModel
  | RadarModel
  | TreemapModel
  | InfoModel
  | SequenceModel
  | GitModel
  | C4Model
  | BlockModel
  | RailroadModel
  | AgentflowModel
  | TreeViewModel
  | CynefinModel
  | WardleyModel
  | EventModelingModel
  | UsecaseModel
  | VennModel
  | IshikawaModel
  | SwimlaneModel;
