// Generated by scripts/gen-registry.mjs.
import type { ArchitectureModel } from './diagrams/architecture/db.js';
import type { ClassModel } from './diagrams/class/types.js';
import type { ErModel } from './diagrams/er/types.js';
import type { FlowchartModel } from './diagrams/flowchart/types.js';
import type { GanttModel } from './diagrams/gantt/types.js';
import type { JourneyModel } from './diagrams/journey/db.js';
import type { KanbanModel } from './diagrams/kanban/db.js';
import type { MindmapModel } from './diagrams/mindmap/db.js';
import type { PieModel } from './diagrams/pie/model.js';
import type { QuadrantModel } from './diagrams/quadrant/db.js';
import type { RequirementModel } from './diagrams/requirement/types.js';
import type { SankeyModel } from './diagrams/sankey/db.js';
import type { StateModel } from './diagrams/state/types.js';
import type { TimelineModel } from './diagrams/timeline/db.js';
import type { XyChartModel } from './diagrams/xychart/db.js';

export type {
  FlowchartModel,
  PieModel,
  ErModel,
  MindmapModel,
  KanbanModel,
  TimelineModel,
  JourneyModel,
  ClassModel,
  QuadrantModel,
  XyChartModel,
  StateModel,
  GanttModel,
  ArchitectureModel,
  RequirementModel,
  SankeyModel,
};

// The union of every implemented diagram's model; narrow it with its `type` field.
export type DiagramModel =
  | FlowchartModel
  | PieModel
  | ErModel
  | MindmapModel
  | KanbanModel
  | TimelineModel
  | JourneyModel
  | ClassModel
  | QuadrantModel
  | XyChartModel
  | StateModel
  | GanttModel
  | ArchitectureModel
  | RequirementModel
  | SankeyModel;
