import type { DiagramType } from '../detect.js';
import type { Diagram } from '../types.js';
import { architecture } from './architecture/index.js';
import { classDiagram } from './class/index.js';
import { er } from './er/index.js';
import { flowchart } from './flowchart/index.js';
import { gantt } from './gantt/index.js';
import { journey } from './journey/index.js';
import { kanban } from './kanban/index.js';
import { mindmap } from './mindmap/index.js';
import { pie } from './pie/index.js';
import { quadrantChart } from './quadrant/index.js';
import { requirement } from './requirement/index.js';
import { sankey } from './sankey/index.js';
import { state } from './state/index.js';
import { timeline } from './timeline/index.js';
import { xychart } from './xychart/index.js';

// Every implemented diagram type. Detection covers more types than this; the rest are unsupported.
// Generated by scripts/gen-registry.mjs.
const all = [
  flowchart,
  pie,
  er,
  mindmap,
  kanban,
  timeline,
  journey,
  classDiagram,
  quadrantChart,
  xychart,
  state,
  gantt,
  architecture,
  requirement,
  sankey,
] as Diagram<unknown>[];

export const diagrams = new Map<DiagramType, Diagram<unknown>>(all.map((d) => [d.type, d]));
