import type { DiagramType } from '../detect.js';
import type { Diagram } from '../types.js';
import { agentflow } from './agentflow/index.js';
import { architecture } from './architecture/index.js';
import { block } from './block/index.js';
import { c4 } from './c4/index.js';
import { classDiagram } from './class/index.js';
import { cynefin } from './cynefin/index.js';
import { er } from './er/index.js';
import { eventmodeling } from './eventmodeling/index.js';
import { flowchart } from './flowchart/index.js';
import { gantt } from './gantt/index.js';
import { gitGraph } from './git/index.js';
import { info } from './info/index.js';
import { ishikawa } from './ishikawa/index.js';
import { journey } from './journey/index.js';
import { kanban } from './kanban/index.js';
import { mindmap } from './mindmap/index.js';
import { packet } from './packet/index.js';
import { pie } from './pie/index.js';
import { quadrantChart } from './quadrant/index.js';
import { radar } from './radar/index.js';
import { railroad } from './railroad/index.js';
import { requirement } from './requirement/index.js';
import { sankey } from './sankey/index.js';
import { sequence } from './sequence/index.js';
import { state } from './state/index.js';
import { swimlane } from './swimlane/index.js';
import { timeline } from './timeline/index.js';
import { treeView } from './treeview/index.js';
import { treemap } from './treemap/index.js';
import { usecase } from './usecase/index.js';
import { venn } from './venn/index.js';
import { wardley } from './wardley/index.js';
import { xychart } from './xychart/index.js';

// Every implemented diagram type. Detection covers more types than this; the rest are unsupported.
// Generated by scripts/gen-registry.mjs.
const all = [
  flowchart,
  pie,
  er,
  mindmap,
  kanban,
  timeline,
  journey,
  classDiagram,
  quadrantChart,
  xychart,
  state,
  gantt,
  architecture,
  requirement,
  sankey,
  packet,
  radar,
  treemap,
  info,
  sequence,
  gitGraph,
  c4,
  block,
  railroad,
  agentflow,
  treeView,
  cynefin,
  wardley,
  eventmodeling,
  usecase,
  venn,
  ishikawa,
  swimlane,
] as Diagram<unknown>[];

export const diagrams = new Map<DiagramType, Diagram<unknown>>(all.map((d) => [d.type, d]));
