// Ported from Mermaid mermaid@12.1.0 (21f72f07ea), packages/mermaid/src/diagrams/block/blockDB.spec.ts
// Copyright (c) 2014 - 2022 Knut Sveidqvist, MIT License. Generated by scripts/sync-specs.mjs; do not edit.
import { describe, it, expect, vi, afterEach } from 'vitest';
import * as diagramAPI from './config.js';
import { db } from './adapter.js';

describe('block db edge styles', () => {
  it('should correctly identify edge thickness', () => {
    expect(db.edgeStrToThickness('-->')).toBe('normal');
    expect(db.edgeStrToThickness('-.->')).toBe('normal');
    expect(db.edgeStrToThickness('==>')).toBe('thick');
  });

  it('should correctly identify edge patterns', () => {
    expect(db.edgeStrToPattern('-->')).toBe('solid');
    expect(db.edgeStrToPattern('==>')).toBe('solid');
    expect(db.edgeStrToPattern('-.->')).toBe('dotted');
  });

  it('should correctly identify start and end arrows', () => {
    expect(db.edgeStrToEdgeStartData('<-->')).toBe('arrow_point');
    expect(db.edgeStrToEdgeData('<-->')).toBe('arrow_point');

    expect(db.edgeStrToEdgeStartData('<==>')).toBe('arrow_point');
    expect(db.edgeStrToEdgeData('<==>')).toBe('arrow_point');

    expect(db.edgeStrToEdgeStartData('-->')).toBe('arrow_open');
    expect(db.edgeStrToEdgeData('-->')).toBe('arrow_point');

    expect(db.edgeStrToEdgeData('--x')).toBe('arrow_cross');
    expect(db.edgeStrToEdgeData('--o')).toBe('arrow_circle');
  });
});

describe('block db runtime config', () => {
  afterEach(() => {
    vi.restoreAllMocks();
    db.clear();
  });

  it.skip('should call getConfig at sanitization time, not at module load time', () => {
    const spy = vi.spyOn(diagramAPI, 'getConfig').mockReturnValue({} as any);

    db.setHierarchy([{ id: 'a', type: 'square', label: 'hello', children: [] }]);

    // getConfig must have been called during setHierarchy (call-time read),
    // not only once at module import time.
    expect(spy).toHaveBeenCalled();
  });
});
